application: ieee80211timeline
version: 1
runtime: python
api_version: 1

default_expiration: '365d'

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /_ah/queue/deferred
  script: djangoappengine/deferred/handler.py
  login: admin
  
- url: /profile/.*
  script: user_profile.py
  login: required

- url: /media/admin
  static_dir: django/contrib/admin/media/

- url: /timeline/.*
  script: djangoappengine/main/main.py
  
- url: /.*
  script: djangoappengine/main/main.py
  
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
