application: ieee80211timeline
version: 2
runtime: python
api_version: 1

default_expiration: '365d'

builtins:
- datastore_admin: on
- admin_redirect: on
 
handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /_ah/queue/deferred
  script: djangoappengine/deferred/handler.py
  login: admin
  
- url: /media/admin
  static_dir: django/contrib/admin/media/

- url: /timeline/dn
  script: djangoappengine/main/main.py
  login: admin
  
- url: /ballot/dn
  script: djangoappengine/main/main.py
  login: admin
  
- url: /util/import/work
  script: djangoappengine/main/main.py
  login: admin
  
- url: /media/images
  static_dir: media/images/

- url: /favicon.ico
  static_files: media/images/favicon.ico
  upload: media/images/favicon.ico

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
  secure: optional
  expiration: '0'
  
- url: /.*
  script: djangoappengine/main/main.py
  
admin_console:
  pages:
  - name: Django Admin
    url: /admin
     
  